contact/urls.py
from django.urls import path
from contact import views

app_name = 'contact'

urlpatterns = [
	path('', views.contact_view, name='contact_view'),
	path('confirmation/', views.confirmation_view, name='confirmation_view')
]

showcase/urls.py
from django.urls import path
from showcase import views

app_name = 'showcase'

urlpatterns = [
	path('', views.home, name='home'),
	path('page/<slug:slug>', views.subpage, name='subpage'),
	path('credits', views.credits_view, name='credits')
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="">
	<meta name="author" content="">

	{% block title %}
		<title>Accueil</title>
	{% endblock %}

	<!-- Bootstrap core CSS -->
	<link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

	<!-- Custom fonts for this template -->
	<link rel="stylesheet" type="text/css" href="{% static 'fork-awesome/css/fork-awesome.css' %}">
	<!--<link href="{% static 'fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">-->
	<!-- <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'> -->
	<!-- <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'> -->

	<!-- Custom styles for this template -->
	<link href="{% static 'css/clean-blog.css' %}" rel="stylesheet">

	{% block additional_css %}
	{% endblock %}

</head>

<body>
	<!-- Navigation -->
	<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
		<div class="container">
			<a class="navbar-brand" href="{% url 'showcase:home' %}"><img class="img-fluid logo" src="{% static 'img/logo-reduced-transparent.png' %}" alt="logo diagnostic immobilier 77"></img></a>
			<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
				Menu
				<i class="fa fa-lg fa-angle-down"></i>
			</button>
			<div class="collapse navbar-collapse" id="navbarResponsive">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item">
						<a id="diagnostiques" class="nav-link" href="#">Les diagnostiques <i class="fa fa-lg fa-angle-down"></i></a>
						<ul class="submenu">
							{% for subpage in subpages %}
								{% if subpage.menu_id == 'diagnostiques' %}
									<li class="submenu-item"><a href="{% url 'showcase:subpage' slug=subpage.slug %}">{{ subpage.title }}</a></li>
								{% endif %}
							{% endfor %}
						</ul>
					</li>
					<li class="nav-item">
						<a id="obligations" class="nav-link" href="#">Vos obligations <i class="fa fa-lg fa-angle-down"></i></a>
						<ul class="submenu">
							{% for subpage in subpages %}
								{% if subpage.menu_id == 'obligations' %}
									<li class="submenu-item"><a href="{% url 'showcase:subpage' slug=subpage.slug %}">{{ subpage.title }}</a></li>
								{% endif %}
							{% endfor %}
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'contact:contact_view' %}">Contact</a>
					</li>
				</ul>
			</div>
			<button id="backtop" class="btn backtop"><span class="fa fa-2x fa-arrow-up"></span></button>
		</div>
	</nav>

	{% block header %}
	{% endblock %}

	{% block content %}
	{% endblock %}

	<hr>

	{% block footer %}
	<!-- Footer -->
	<footer>
		<div class="container">
            <div class="row">
                <div class="col-12">
                    <p class="text-center">Retrouvez Sasu Diag Immo77 sur:</p>
                </div>
            </div>
			<div class="row">
				<div class="col-lg-8 col-md-10 mx-auto">
					<ul class="list-inline text-center">
						<li class="list-inline-item">
							<a href="https://www.facebook.com/Sasu-Diag-Immo77-101139334663162/">
								<span class="fa fa-2x fa-facebook"></span>
							</a>
						</li>
					</ul>
					<p class="copyright text-muted">Copyleft &copy Sasu Diag Immo</p>
					<p class="copyright text-muted">
						<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
							<img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
						</a>
						<br />
						Le code du site est sous license
						<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">Creative Commons Attribution-ShareAlike 4.0 International License</a>.
						<br />
						Le site est basé sur le template
							<a href="https://startbootstrap.com/themes/clean-blog/">
								Clean Blog du site startbootstrap.com
							</a>
						distribué librement sous
						<a href="https://opensource.org/licenses/mit-license.php">License MIT</a>
						<br />
						<a href="{% url 'showcase:credits' %}">Crédits supplémentaires</a>
					</p>
				</div>
			</div>
		</div>
	</footer>
	{% endblock %}

	<!-- Bootstrap core JavaScript -->
	<script src="{% static 'jquery/jquery.min.js' %}"></script>
	<script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>

	<!-- Custom scripts for this template -->
	<script src="{% static 'js/clean-blog.js' %}"></script>
	<script src="{% static 'js/back_to_top_scroller.js' %}" type="text/javascript"></script>

	{% block additional_script %}
	{% endblock %}

</body>

</html>